conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('plataforma/', include('vismet.urls')),
    path('', include('home.urls')),
    path('arquivos/', include('directory.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.IndexView, name='index')
]

vismet/urls.py
from django.urls import path, include
from . import views

app_name = 'vismet'

urlpatterns = [
     path('', views.VisMetView, name='vismet'),

     path('api/opcoes/', views.Api_Data_Options, name='data_options'),
     path('api/estacoes/', views.Api_Stations, name='api_stations'),
     path('api/estacoes/<format>/<source>/<type>/', views.Api_Stations_Source.as_view(), name='api_stations_source'),
     path('api/estacoes/<str:format>/<str:source>/<str:code>/<int:start_day>-<int:start_month>-<int:start_year>/<int:final_day>-<int:final_month>-<int:final_year>/',
          views.Api_Stations_Data,
          name='api_station_data'),

     path('api/pixels/', views.Api_Pixel.as_view(), name='pixels'),
     path('api/pixels025/', views.Pixel25.as_view(), name='pixels-025'),
     path('api/pixels01/', views.Pixel01.as_view(), name='pixels-01'),
     path('api/pixels/<str:format>/<int:pk>/<str:data_model>/<int:start_day>-<int:start_month>-<int:start_year>/<int:final_day>-<int:final_month>-<int:final_year>/',
          views.Api_Pixel_Data),

     path('api/cities/', views.Api_Cities.as_view(), name='cities'),
     path('api/cities/<str:format>/<str:name>/<str:data_model>/<int:start_day>-<int:start_month>-<int:start_year>/<int:final_day>-<int:final_month>-<int:final_year>/',
         views.Api_Cities_PixelData),

     # Esta url será a url principal para a api (em andamento)
     path('api/', include('vismet.api.urls'), name='api'),
]

home/views.py
from django.shortcuts import render
from vismet.models import ElementCategory

def IndexView(request):
    categories = ElementCategory.objects.all().order_by('pk')
    return render(request, 'home/index.html', {'categories': categories})

home/templates/includes/footer.html
{% load static %}
<footer id="footer">
  <a class="anchor" id="fo"></a>
    <link rel="stylesheet" href="{% static 'home/css/fontawesome_all.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/academicons.min.css' %}">
    <div class="container">
      <ul class="copyright">
        <li>
          Design by<br>
          Daniel Viviroli<br>
          CC BY-NC-SA<br>
          <br>
          <a target="_blank" rel="noopener noreferrer" href="https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode">
            <i class="fab fa-creative-commons fa-lg"></i>
            <i class="fab fa-creative-commons-by fa-lg"></i>
            <i class="fab fa-creative-commons-nc fa-lg"></i>
            <i class="fab fa-creative-commons-sa fa-lg"></i>
          </a>
        </li>
        <li style="text-align:left">
            <i class="fas fa-home fa-sm"></i>
            <a target="_blank" rel="noopener noreferrer" href="http://impactoclima.ufes.br">IEC-UFES</a>
            <i class="fas fa-home fa-sm" style="opacity:0.0"></i>
            <i class="fas fa-home fa-sm" style="opacity:0.0"></i>
            <br>Universidade Federal do Espírito Santo
            <i class="fas fa-home fa-sm" style="opacity:0.0"></i>
            <br>Av. Fernando Ferrari, 514
            <br>Goiabeiras, Vitória - ES | CEP 29075-910
            <i class="fas fa-home fa-sm" style="opacity:0.0"></i>
            <br>Brazil
        </li>
        <li style="text-align:left">
            <a target="_blank" rel="noopener noreferrer" href="mailto:clima.ufes@gmail.com"><i class="far fa-envelope fa-sm"></i> email</a><br>
            <a target="_blank" rel="noopener noreferrer" href="https://twitter.com/katarenamatos"><i class="fab fa-twitter fa-am"></i> @impactoclima</a><br>
            <br>
            <br>
            <br>
        </li>
      </ul>
    </div>
</footer>

home/templates/includes/navbar.html
{% load static %}
<header id="header" class="alt">
  <h1>IEC-ES</h1>

  <nav id="nav">
    <ul>
        <li><a href="{% url 'home:index' %}">Home</a></li>
        <li><a href="{% url 'vismet:vismet' %}">Plataforma</a></li>
    </ul>
  </nav>
</header>
<a href="#menu" class="navPanelToggle"><span class="fa fa-bars"></span></a>